### PR TITLE
WIP: Windows and Linux support

### PR DESCRIPTION
**Pull request by ranjanan**
This PR aims to add windows support, include support for creating an installer using `makensis`. There are two major things that the PR does: 
1. Provide a simple bundling script (agnostic to both Windows and Linux)
2. Provide a sample installer that will simply compress, ship and compress the bundle. 

#### The `bundle` API: 
A program to create a blink bundle would look something like this: 
```julia
using Bundler

# Libraries

libraries = [joinpath(Pkg.dir("Blink"), "deps", "atom"), 
			 joinpath(Pkg.dir("HttpParser"), "deps", "usr", "lib", "libhttp_parser64.DLL"),
			 joinpath(Pkg.dir("MbedTLS"), "deps", "usr", "lib", "libmbedtls.dll"),
			 joinpath(Pkg.dir("MbedTLS"), "deps", "usr", "lib", "libmbedcrypto.dll"),
			 joinpath(Pkg.dir("MbedTLS"), "deps", "usr", "lib", "libmbedx509.dll")]
resources = [joinpath(Pkg.dir("Blink"), "res", "blink.js"),
			 joinpath(Pkg.dir("Blink"), "res", "spinner.css"),
			 joinpath(Pkg.dir("Blink"), "res", "reset.css"),
			 joinpath(Pkg.dir("Blink"), "res", "blink.css"), 
			 joinpath(Pkg.dir("Blink"), "src", "content", "main.html"),
			 joinpath(Pkg.dir("Blink"), "src", "AtomShell", "main.js")]

bundle(joinpath(dirname(@__FILE__), "blink.jl"), 
	resources = resources, libraries = libraries, create_installer = true) # need to specify full path, but got to handle that internally instead

```
I was wondering what you think about using this as the main API for the package. 

This is still WIP, but thoughts, comments and suggestions are more than welcome.

### CODE REVIEW

**Comment by NHDaly** [comment]
Hey, sorry i didn't respond for almost a week!

Yeah, I think this is really cool. I agree, this seems like it could be a much nicer API! Even though the current HEAD version presents a command-line interface, for a real project the command is long enough that I ended up putting it in a file, [build.sh](https://github.com/NHDaly/PaddleBattleJL/blob/7543e9f7f9a61998166891c8f52c0b2ec5975090/build.sh), which definitely makes me think having a package api like you suggested above would be good! :)

----

As far as naming goes, the reason I ultimately named the package `ApplicationBuilder`, not `ApplicationBundler`, was because it actually does do the building as well: it invokes PackageCompiler to compile the app, and then it creates the bundle itself. So to me, bundling is like, one step, but this does both the compiling and the bundling, so that's why I called it `Builder`.

Would `build_app()` be a reasonable api function name? or `build_bundle`, perhaps? `build_app_bundle`?

**Comment by NHDaly** [comment]
Another thing I was thinking about, is that right now we are using the `ApplicationBuilder` package to provide code that the _actual app itself_ would call (`change_dir_if_bundle()`). Is it weird to mix that with code we expect a static "build script" to call?

Is it possible for a Package to provide multiple sibling modules? Or does everything have to be a child module of the Package name (`ApplicationBuilder.BuildBundle` or the other way around or something..)?

**Comment by NHDaly** [comment]
> or the other way around
Maybe we could put `change_dir_if_bundle()` into something like `ApplicationBuilder.Runtime`?

**Comment by ranjanan** [comment]
> Would build_app() be a reasonable api function name? or build_bundle, perhaps? build_app_bundle? 

Sure, I think I'll just rename it as `build_app`. You're right, it's not only bundling, but building as well. 

> Is it weird to mix that with code we expect a static "build script" to call?

I guess you are referring to fact that now we now need two build scripts instead of one, and yes I do admit that's not ideal. One of the reasons I initially thought of using `bundle` is because there are two major scripts here: one for building (that's fed into PackageCompiler) and a bundling script, which is the one I pasted here. I'm not really sure how to resolve it, but I think it also gets the job done for now, and I'd be more than happy registering a package that works reliably but inelegantly, and then iterate to refine it from there.  In any case, I believe we'll have more work to do once 1.0 releases too 😄

**Comment by NHDaly** [comment]
Hi @ranjanan, have you been working on this at all lately?

I would like to have windows support working within the next week or so.. I've finally gotten around to installing Boot Camp on my MacBook so now I have a windows machine too! :) I just installed julia and i'm itching to try to set up ApplicationBuilder to work here too. 😈 😈

I would be happy to just merge in whatever you have now (as long as it's guarded behind an `iswindows()`, and then we can maybe work on windows support together! What do you think? Thanks!

**Comment by ranjanan** [comment]
@NHDaly my sincere apologies for no updates. As I mentioned, I've been moving cities and getting ready for graduate school, so a lot of commitments. 

I actually have something working at the moment, so I will just modify this PR in the next few days (promise!) with the working code and you can play with it.

**Comment by NHDaly** [comment]
😄 Hey, no problem at all!! I also just finished moving cities, and then had a 2 and a half week vacation for a wedding, so I can empathize. :)

Yeah, windows support seems like it shouldn't be too tough! Don't worry too much about formatting or whatever, feel free to just splat whatever you have and I can work on it too since you're busy. :) Thanks again for your help!!

Hope your move is going well!! Good luck with everything! (And maybe I'll see you here in the Boston area in a month or so!)

**Comment by ranjanan** [comment]
@NHDaly you can merge this now. The windows and linux stuff is in a `@static` check.

**Comment by NHDaly** [comment]
Thanks Ranjan, this is amazing! :)

I'll start merging it in right now.
Can I move the code you added to the BuildApp submodule, though? That way it's in the same place as the mac build_add_bundle function.

**Comment by ranjanan** [comment]
Sure, go ahead. Thank you for your patience! :)

**Comment by NHDaly** [comment]
Haha, no way, thank _you_ for your help!! :)

**Comment by NHDaly** [comment]
> Can I move the code you added to the BuildApp submodule, though? That way it's in the same place as the mac build_add_bundle function.

And never mind, on a closer inspection you already had it exactly how I would've done it. :) The only thing I moved is the `export` line: 29ebd2a20062c4fafff7bae0d50c179460500ce5. Cheers!

**Pull request merged**
