### PR TITLE
julia 1.0 support: Merge "build-time" and "run-time" modules BuildApp and App into ApplicationBuilder

### PR DESCRIPTION
**Pull request by NHDaly**
Split out `change_dir_if_bundle` into a new package,
[`ApplicationBuilderRuntimeUtils.jl`](https://github.com/NHDaly/ApplicationBuilderRuntimeUtils.jl).

This way, there's not the weird inner package `BuildApp`, which has almost the
same name as ApplicationBuilder, and I think is sort of confusing. I think
doing it this way really clears up the dependency relationship between the two
modules, and still allows application-code to only import the runtime
dependencies!

### CODE REVIEW

**Comment by NHDaly** [comment]
😄 Haha awesome, thanks for dropping in!! :D

> just rename the inner module to `RuntimeUtils`

Ah, so that's exactly the problem: that's not how it's currently structured even though it _should_ be. Currently (at HEAD), it's the _outer module_ that holds the "runtime utils" (`ApplicationBuilder`) and the "inner", or really _"sibling"_ module that holds the actual build functionality (`BuildApp`).

The reasoning is this:

1. A user application file that's being compiled _shouldn't_ be importing the build functionality, otherwise all that logic will get compiled into the program unnecessarily. (And not only is that slow, also right now the [build stuff doesn't compile](https://github.com/JuliaLang/PackageCompiler.jl/issues/78), so it will break things.)
2. In order to import an "inner module" (ie `module Foo module Bar end end`) you _have_ to also import the outer one -- that is, there is no way to import `Foo.Bar` without also loading, and initializing, all the code in `Foo`.
3. Following from `1.` and `2.`, `RuntimeUtils` cannot be an inner module of `ApplicationBuilder`, or an application wouldn't have access to `RuntimeUtils`.
4. BUT even crazier, there's no way to import an outer module without also evaluating and initializing all the code in the _inner module_! i.e., calling `import Foo` would still cause the module `Bar` to be included in the compiled binary.
5. Following from `4.`, then, the build-functionality (`BuildApp`) also cannot be a standard "inner module" either!

To rephrase `1`-`5`, neither `BuildFunctionality.RuntimeUtils` nor `RuntimeUtils.BuildFunctionality` are acceptable structures.

SO what we've done so far is have them as _"siblings"_. That is, the "outer module", `ApplicationBuilder` does two things: A) it contains all the runtime utilities, and B) it adds the sibling module `BuildApp` to the LOAD_PATH, here:
https://github.com/NHDaly/ApplicationBuilder.jl/blob/2ddc651fa2e14c747f39186f4122f613f557baeb/src/ApplicationBuilder.jl#L14

So then, you can now get the runtime utilities by first importing `ApplicationBuilder`, then importing `BuildApp`:
```julia
using ApplicationBuilder; using BuildApp
```

But i think that's still not great. First of all, it's non-standard, so here's an understandability drawback. Second, it's brittle: if you flip the order of those `using` statements, it fails. That's weird. Third, it's weird that the names are so similar. Really the outer module should be called `ApplicationBuilderRuntimeUtils`, but it's required that the outer module name match the name of the Package, and currently the package provides both the runtime utilities *and* the build functionality.


> I can't imagine it getting used by other packages, so it seems silly to maintain it separate from this. It also sounds like the name confusion is the main reason to split it out.

Yeah, so you're right that _confusion_ is my main motivation for splitting it out. It's all the weirdness that I described above, including the name part. Also, the reason I first started doing it was that I had a problem with docstrings not showing up, and someone on slack said this might fix it, but it didn't...


> If you wanted stricter separation, you could even house it in a directory under src.

I'm interested in this. What do you mean by that? I'm open to other suggestions for how to proceed.

--------

I do think splitting them up is a bit cleaner, but the things I don't like about it are α) that on `julia v0.7` users will have to manually `add` both packages in order to use both (on v0.6 that's not a problem since ApplicationBuilder installs the other as a dependency), β) it'll be a bit weirder to maintain both separately, and ɣ) the `ApplicationBuilderRuntimeUtils` name is super long.

But I _do_ like that everything becomes more standard, so I'm currently leaning towards this being a good idea. What do you think? :) Thanks for jumping in here with me!!

**Comment by ranjanan** [comment]
@NHDaly, are you not able to implement this way? 

```julia

module ApplicationBuilder
module BuildUtils
...
end
module RuntimeUtils
...
end
end

**Comment by NHDaly** [comment]
Unfortunately no. That's what we had at first, and it causes both submodules to be loaded and compiled when the outer module is imported. I actually can't find any documentation for that behavior in the manual (https://docs.julialang.org/en/release-0.6/manual/modules/), but that seems to be the case based on my simple experimentation. Consider:

```julia
julia> module Outer
    println("compiling Outer")
    module A
      println("compiling A")
    end
    module B
      println("compiling B")
    end
end
compiling Outer
compiling A
compiling B
>> Outer
```
So the problem is that in order for an app to import `ApplicationBuilder.RuntimeUtils`, PackageCompiler would end up also attempting to compile `ApplicationBuilder.BuildUtils`, which eventually means it attempts to compile itself (PackageCompiler), which currently fails on `v0.6`. And also it would mean (i'm pretty sure) that the resultant binary would contain all of the compiled code for BuildUtils and PackageCompiler, which it just doesn't need.

**Comment by NHDaly** [comment]
Here's what I'm talking about in the actual code. I've made the change we're talking about here:
dee26b2bacafbb060b58de87be12e8dbc3569cd8

And this is the failure:
```julia
julia> using ApplicationBuilder.BuildApp
PARSING (&& COMPILING) ApplicationBuilder
PARSING (&& COMPILING) BuildApp

julia> build_app_bundle("/Users/Daly/.julia/v0.6/ApplicationBuilder/examples/hello.jl")
...
PARSING (&& COMPILING) ApplicationBuilder
PARSING (&& COMPILING) BuildApp
ERROR: LoadError: LoadError: LoadError: LoadError: LoadError: GCC wasn't found. Please make sure that gcc is on the path and run Pkg.build("PackageCompiler")
while loading /Users/daly/.julia/v0.6/PackageCompiler/src/static_julia.jl, in expression starting on line 11
while loading /Users/daly/.julia/v0.6/PackageCompiler/src/PackageCompiler.jl, in expression starting on line 28
while loading /Users/daly/.julia/v0.6/ApplicationBuilder/src/BuildApp.jl, in expression starting on line 5
while loading /Users/daly/.julia/v0.6/ApplicationBuilder/src/ApplicationBuilder.jl, in expression starting on line 16
while loading /Users/Daly/.julia/v0.6/ApplicationBuilder/examples/hello.jl, in expression starting on line 1
ERROR: failed process: Process(`/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia -Cx86-64 -J/Applications/Julia-0.6.app/Contents/Resources/julia
/lib/julia/sys.dylib --compile=yes --depwarn=yes --precompiled=no --compilecache=no --startup-file=no -O3 -g0 --output-o hello.o -e '
  empty!(Base.LOAD_CACHE_PATH) # reset / remove any builtin paths
  push!(Base.LOAD_CACHE_PATH, "cache_ji_v0.6.4") # enable usage of precompiled files
  Sys.__init__(); Base.early_init(); # JULIA_HOME is not defined, initializing manually
  include("/Users/Daly/.julia/v0.6/ApplicationBuilder/examples/hello.jl") # include Julia program file
  empty!(Base.LOAD_CACHE_PATH) # reset / remove build-system-relative paths'`, ProcessExited(1)) [1]
```

It makes me sooooo sadddddd! :(((
Haha thanks for all your help everyone, sorry it's such a weird, annoying problem..

**Comment by NHDaly** [comment]
Okay actually, it turns out that the current approach cannot work in Julia v0.7, because a package cannot modify the `LOAD_PATH` in `Main`.

So i think i'm going to pull the trigger and merge in this PR!!! :)

Reach out to me if you have concerns, but i'm gonna try to do this today before my talk tomorrow! 😂😅😂

**Comment by NHDaly** [comment]
Thanks a million, @non-Jedi. Yeah, thanks, that does make sense. I played around with that as well, but -- as far as I can tell -- it still doesn't make v0.7 (and/or v1.0) happy. :(

So i'm going to play with getting everything to pass as the two separate packages, and if it works out, great! And if in the future, if we figure out a better way to move forward, these can always be re-combined! :)

Thanks again!

**Comment by NHDaly** [comment]
(jk, I've just gone ahead and pushed up a [`julia0.7`](https://github.com/NHDaly/ApplicationBuilder.jl/tree/julia0.7)] for this package instead, which has this merged in, so that you can check it out if you need v0.7 support, but i don't have to worry about breaking things in master. :) )

**Comment by NHDaly** [comment]
OKAY! Good news:
@KristofferC has saved the day! :) Thanks Kristoffer!!

So I've restructured everything, and I think this is going to be the right solution. :) After merging this, we can let it sit for a few days, and then if it looks good, i'll go ahead and officially register it on METADATA! :)

---------------

SO, here's what we did:
Before this PR, the only "runtime-util" that actually exists, is `change_dir_if_bundle`. But honestly, there's no reason for any code to _not_ have that be the default behavior, so we don't even need to expose this to users -- we can just always do it for them! So that's what this PR does, it always injects code into the program to `cd` into Resources before running the user code.

This means that we no longer have any "runtime utilities", so we no longer need two separate modules. Therefore, I've moved _everything_ back into `ApplicationBuilder`, and deleted `BuildApp` and `App`.

---------------

Because this is a breaking change from before, I've also added a `@warn` statement that runs whenever you import ApplicationBuilder, telling you about the change. This warning will now show up at the two places where your code will break due to this change! :)

```julia
(15:08:38) julia0.6> using ApplicationBuilder; using BuildApp  # BuildApp no longer exists
Warning: ApplicationBuilder has changed a bit since julia 0.6:
  - `module BuildApp` has been removed. You should remove `using BuildApp`
      from your build scripts to build with julia v0.7.
  - You should also remove `using ApplicationBuilder` from the source-code of
      programs being built, since the `change_dir_if_bundle` behavior will
      now come default for all applications. `using ApplicationBuilder` in
      your program source may cause it to fail to build.
 This message will be removed in the next version of ApplicationBuilder.
WARNING: Your Julia system image is not compiled natively for this CPU architecture.
        Please run `PackageCompiler.force_native_image!()` for optimal Julia performance
ERROR: ArgumentError: Module BuildApp not found in current path.
Run `Pkg.add("BuildApp")` to install the BuildApp package.
Stacktrace:
 [1] _require(::Symbol) at ./loading.jl:435
 [2] require(::Symbol) at ./loading.jl:405
```
and
```julia
(15:11:38) julia0.6> mktemp() do f,_
                         write(f, """using ApplicationBuilder
                                     Base.@ccallable function julia_main(ARGS::Vector{String})::Cint
                                         ApplicationBuilder.App.change_dir_if_bundle()
                                         println("HELLO!")
                                         return 0
                                     end
                                  """)
                         build_app_bundle(f);
                     end
~~~~~~ Creating mac app in "/Users/daly/Documents/developer/code/games/FTLBSG/builddir/tmpvIhINE.app" ~~~~~~~
~~~~~~ Compiling a binary from '/var/folders/5j/c6kd481j4l71m802wh5qp6vc0000gn/T/tmpvIhINE'... ~~~~~~~
Julia program file:
  "/Users/daly/Documents/developer/code/games/FTLBSG/builddir/tmpvIhINE.app/Contents/MacOS/applicationbuilderutils.jl"
C program file:
  "/Users/daly/.julia/v0.6/ApplicationBuilder/src/program.c"
Build directory:
  "/Users/daly/Documents/developer/code/games/FTLBSG/builddir/tmpvIhINE.app/Contents/MacOS"
Warning: ApplicationBuilder has changed a bit since julia 0.6:
  - `module BuildApp` has been removed. You should remove `using BuildApp`
      from your build scripts to build with julia v0.7.
  - You should also remove `using ApplicationBuilder` from the source-code of
      programs being built, since the `change_dir_if_bundle` behavior will
      now come default for all applications. `using ApplicationBuilder` in
      your program source may cause it to fail to build.
 This message will be removed in the next version of ApplicationBuilder.
ERROR: LoadError: LoadError: LoadError: LoadError: LoadError: GCC wasn't found. Please make sure that gcc is on the path and run Pkg.build("PackageCompiler")
while loading /Users/daly/.julia/v0.6/PackageCompiler/src/static_julia.jl, in expression starting on line 11
while loading /Users/daly/.julia/v0.6/PackageCompiler/src/PackageCompiler.jl, in expression starting on line 28
...
ERROR: failed process: Process(`/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia -Cx86-64 -J/Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --pr
...
```

------------

So I'm going to merge this in now once CI passes! :) And then i'll cut a new version, and after a few days we can add this to METADATA and maybe remove the warnings then.

**Comment by NHDaly** [comment]
@ranjanan  does that all look good to you too? :) It was fun to hang out over last week!!

**Pull request merged**
